# Generated by Django 4.2.6 on 2023-10-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortner',
            fields=[
                ('long_url', models.URLField(primary_key=True, serialize=False)),
                ('short_code', models.CharField(max_length=300, unique=True)),
            ],
        ),
    ]
